# workflow to run ./site/ebook.sh on push to master. Requires python and pandocname: Generate eBook

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: install bs4
      run: |
        pip install beautifulsoup4

    - name: Install pandoc and LuaLaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-luatex

    - name: Run ebook script
      working-directory: site
      run: |
        ./ebook.sh 
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: book
        path: site/book.epub

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: book
        path: site/book.pdf