# workflow to run ./site/ebook.sh on push to master. Requires python and pandocname: Generate eBook

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.122

    - name: install bs4
      run: |
        pip install beautifulsoup4

    - name: Install pandoc
      run: |
        sudo apt-get install -y pandoc

    - name: Run ebook script
      run: |
        ./site/ebook.sh 
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: book
        path: site/book.epub
